// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_MapGenerator","status":true,"description":"自動マップ生成 1.1.9\r\n自動的にマップを生成しイベントを配置します。","parameters":{"WallHight":"1","MinRoomSize":"5","MaxRoomSize":"10","ShowOuterWall":"ON"}}
];
